### ISSUE TITLE
No Guild icon needed on the personal bar

### ISSUE THREAD

**Issue by tflo** [peterwooley/KUI_FriendHighlight#1]
I think you agree with me that the Guild icon should not be displayed on the personal bar (aka Personal Resource Display), as it is somewhat logic that my current toon is in the same guild as my current toon:

<img width="458" alt="image" src="https://github.com/user-attachments/assets/2cb22c5b-ed2a-4b67-b001-309c3dabef6d">

Only tested for one day, but this simple check seems to fix it fine:

```diff
diff --git a/KUI_FriendHighlight/KUI_FriendHighlight.lua b/KUI_FriendHighlight/KUI_FriendHighlight.lua
--- a/KUI_FriendHighlight/KUI_FriendHighlight.lua
+++ b/KUI_FriendHighlight/KUI_FriendHighlight.lua
@@ -7,9 +7,9 @@
 local function Frame_UpdateGuildText(f)
     f.FriendHighlight_UpdateGuildText(f);
 
-    if UnitIsPlayer(f.unit) then
+    if UnitIsPlayer(f.unit) and not UnitIsUnit(f.unit, 'player') then
         local friend = C_FriendList.IsFriend(UnitGUID(f.unit))
         if friend then
             mod:ShowFriendIcon(f)
             return
         end
```

**Comment by peterwooley** [comment]
Thanks for catching this and working up a fix. Truth be told, it took me quite a while to remember how to turn Personal Resource Display back on to test it!

Fixed in [1.0.18](https://legacy.curseforge.com/wow/addons/kui_friendhighlight/files/5895711).
